before:
  hooks:

builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

brews:
  - name: spark

    tap:
      owner: chevalmuscle
      name: homebrew-spark-idea

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    custom_block: |
      head do
        url "https://github.com/chevalmuscke/spark.git"
        depends_on "go"
      end
    # Your app's description.
    # Default is empty.
    description: "A simple cli to input and store your ideas directly with git and without a text editor"

    skip_upload: auto

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
